name: tarefas_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  go_router: ^6.2.0
  intl: ^0.17.0
  modal_bottom_sheet: ^3.0.0-pre
  uuid: ^3.0.7
  table_calendar: ^3.0.8
  flutter_calendar_carousel: ^2.4.1
  flutter_circular_slider: ^2.5.0
  search_cep: ^4.0.1
  brasil_fields: ^1.9.1
  flutter_styled_toast: ^2.1.3
  flutter_masked_text2: ^0.9.1
  url_launcher: ^6.1.10
  flutter_time_range: ^0.0.3
  camera_camera: ^3.0.0-dev
  image_picker: ^0.8.7
  get: ^4.6.5
  camera: ^0.10.3+2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_ui_firestore: ^1.3.0
  skeleton_animation: ^0.1.4
  google_sign_in: ^6.0.2
  google_sign_in_android: ^6.1.8
  provider: ^6.0.5
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0
  grouped_list: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

flutter_native_splash: # flutter pub run flutter_native_splash:create
  color: "#121212"
  image: "assets/app/icon-splash.png"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/icon-app.png"

flutter_launcher_icons: # flutter pub run flutter_launcher_icons
  min_sdk_android: 21
  image_path: "assets/app/icon-app.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/app/icon-android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app/
    - assets/icons/
    - assets/images/

  fonts:
    - family: ElementalSansPro
      fonts:
        - asset: assets/fonts/ElementalSansPro.ttf
